### ISSUE TITLE
Recipe App

### ISSUE THREAD

**Issue by SaneMyburg** [SaneMyburg/Recipe-App#13]
[Kanban Board Link](https://github.com/users/SaneMyburg/projects/4/views/1)

We are a group of 2 in a team
@SaneMyburg  and @BANCUNGUYE66

**Comment by DammyShittu** [comment]
Hi @SaneMyburg and @BANCUNGUYE66,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### In your issue you failed to add the link to the kanban project. Kindly do that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your **RoR group project: set up your Kanban board** is ready! Congratulations!  🎉💯🌟 

## Highlights 🎯
💠 Created cards per project requirements!
💠 Fairly distributed tasks!

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
